package com.bnpaper.agento.audit;

public enum AuditAction {
    CONTENT_GENERATED,
    CONTENT_APPROVED,
    CONTENT_REJECTED,
    CONTENT_DELETED,
    WORKFLOW_STARTED,
    WORKFLOW_CANCELLED,
    WORKFLOW_RETRIED,
    KNOWLEDGE_CREATED,
    KNOWLEDGE_UPDATED,
    KNOWLEDGE_ARCHIVED,
    KNOWLEDGE_DELETED,
    EXPORT_STARTED,
    USER_LOGIN,
    USER_CREATED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
}
